# Generated by Django 6.0.4 on 2026-05-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='reportimage',
            name='is_before',
        ),
        migrations.AddField(
            model_name='reportimage',
            name='image_type',
            field=models.CharField(choices=[('before', 'Before'), ('after', 'After')], default='before', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='url',
            field=models.URLField(),
        ),
    ]
